spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pfe
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update


server:
  port: 9191